'use client';

import { useState } from 'react';
import { ArrowLeft, Check, ExternalLink, ImageUp, LoaderCircle, Pencil, Save, Trash2 } from 'lucide-react';
import { feature } from 'topojson-client';
import { geoNaturalEarth1, geoPath } from 'd3-geo';
import world from 'world-atlas/countries-110m.json';
import { exerciseLabels, type Exercise, type LiftEntry, type Place, type Project, type Publication, type SiteData } from '@/lib/site-data';

type Resource = 'profile'|'projects'|'publications'|'places'|'lifts';
type SaveCommand = { resource: Resource; action: 'create'|'update'|'delete'; id?: number; data?: unknown };

export function DashboardClient({ initialData, ownerName, signOutPath }: { initialData: SiteData; ownerName: string; signOutPath: string }) {
  const [data,setData] = useState(initialData); const [tab,setTab] = useState<Resource>('profile'); const [busy,setBusy] = useState(false); const [notice,setNotice] = useState('');
  async function command(body: SaveCommand) { setBusy(true); setNotice(''); try { const response = await fetch('/api/admin/content',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}); const payload = await response.json() as SiteData | { error: string }; if(!response.ok || 'error' in payload) throw new Error('error' in payload ? payload.error : 'Unable to save'); setData(payload); setNotice('Saved'); } catch(error) { setNotice(error instanceof Error ? error.message : 'Unable to save'); } finally { setBusy(false); } }
  return <main className="dashboard-shell"><header className="dashboard-header"><a href="/"><ArrowLeft size={17}/> Back to atlas</a><div><strong>Portfolio field desk</strong><span>Signed in as {ownerName}</span></div><a href={signOutPath}>Sign out</a></header><div className="dashboard-layout"><aside><p>Manage</p>{(['profile','projects','publications','places','lifts'] as Resource[]).map((key)=><button key={key} className={tab===key?'active':''} onClick={()=>{setTab(key);setNotice('')}}>{key==='lifts'?'Strength log':key}</button>)}<a href="/" target="_blank">Open public site <ExternalLink size={14}/></a></aside><section className="dashboard-content">{notice&&<div className={notice==='Saved'?'dashboard-notice success':'dashboard-notice'}>{notice==='Saved'?<Check size={16}/>:null}{notice}</div>}{tab==='profile'&&<ProfileForm data={data} busy={busy} onSave={command}/>} {tab==='projects'&&<ProjectEditor items={data.projects} busy={busy} onSave={command}/>} {tab==='publications'&&<PublicationEditor items={data.publications} busy={busy} onSave={command}/>} {tab==='places'&&<PlaceEditor items={data.places} busy={busy} onSave={command}/>} {tab==='lifts'&&<LiftEditor items={data.lifts} busy={busy} onSave={command}/>}</section></div></main>;
}

function Heading({ eyebrow,title,copy }: {eyebrow:string;title:string;copy:string}) { return <div className="dashboard-title"><span>{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div>; }
function Input({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement>&{label:string}) { return <label>{label}<input {...props}/></label>; }
function Textarea({ label, ...props }: React.TextareaHTMLAttributes<HTMLTextAreaElement>&{label:string}) { return <label>{label}<textarea {...props}/></label>; }
function Submit({ busy,label='Save changes' }: {busy:boolean;label?:string}) { return <button className="save-button" disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Save/>}{label}</button>; }

async function uploadImage(file: File) { const body=new FormData();body.append('file',file);const response=await fetch('/api/admin/upload',{method:'POST',body});const payload=await response.json() as { key?: string; error?: string };if(!response.ok||!payload.key)throw new Error(payload.error||'Upload failed');return payload.key; }
function ImageField({ value,onChange }: {value:string|null;onChange:(key:string)=>void}) { const [loading,setLoading]=useState(false); return <label className="image-field"><span><ImageUp size={18}/> Optional image</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={async(e)=>{const file=e.target.files?.[0];if(!file)return;setLoading(true);try{onChange(await uploadImage(file));}finally{setLoading(false)}}}/>{loading?'Uploading…':value?'Image attached':'JPG, PNG, or WebP · max 5 MB'}</label>; }

function ProfileForm({data,busy,onSave}:{data:SiteData;busy:boolean;onSave:(c:SaveCommand)=>void}) { const p=data.profile;const [imageKey,setImageKey]=useState(p.profileImageKey);return <><Heading eyebrow="Profile" title="The public introduction" copy="These fields power the hero, About section, and contact block."/><form className="editor-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({resource:'profile',action:'update',data:{name:f.get('name'),tagline:f.get('tagline'),shortBio:f.get('shortBio'),longBio:f.get('longBio'),location:f.get('location'),email:f.get('email'),phone:f.get('phone'),githubUrl:f.get('githubUrl'),scholarUrl:f.get('scholarUrl'),linkedinUrl:f.get('linkedinUrl'),profileImageKey:imageKey}})}}><div className="form-grid"><Input label="Name" name="name" defaultValue={p.name} required/><Input label="Tagline" name="tagline" defaultValue={p.tagline} required/><Input label="Location" name="location" defaultValue={p.location} required/><Input label="Email" name="email" type="email" defaultValue={p.email} required/><Input label="Phone" name="phone" defaultValue={p.phone??''}/><Input label="GitHub URL" name="githubUrl" type="url" defaultValue={p.githubUrl} required/><Input label="Google Scholar URL" name="scholarUrl" type="url" defaultValue={p.scholarUrl} required/><Input label="LinkedIn URL" name="linkedinUrl" type="url" defaultValue={p.linkedinUrl??''}/></div><Textarea label="Short biography" name="shortBio" defaultValue={p.shortBio} rows={4} required/><Textarea label="Full About Me" name="longBio" defaultValue={p.longBio} rows={8} required/><ImageField value={imageKey} onChange={setImageKey}/><Submit busy={busy}/></form></> }

function ItemList<T extends {id:number;title?:string;city?:string;date?:string;exercise?:string}>({items,onEdit,onDelete}:{items:T[];onEdit:(item:T)=>void;onDelete:(id:number)=>void}) { return <div className="admin-list">{items.map(item=><div key={item.id}><span>{item.title??item.city??`${item.date} · ${item.exercise}`}</span><div><button onClick={()=>onEdit(item)} aria-label="Edit"><Pencil size={15}/></button><button onClick={()=>onDelete(item.id)} aria-label="Delete"><Trash2 size={15}/></button></div></div>)}</div>; }

function ProjectEditor({items,busy,onSave}:{items:Project[];busy:boolean;onSave:(c:SaveCommand)=>void}) { const [edit,setEdit]=useState<Project|null>(null);const [imageKey,setImageKey]=useState<string|null>(null); const select=(item:Project|null)=>{setEdit(item);setImageKey(item?.imageKey??null)}; return <><Heading eyebrow="Projects" title="The workshop catalog" copy="Curate the repositories and products that best represent your work."/><ItemList items={items} onEdit={select} onDelete={id=>onSave({resource:'projects',action:'delete',id})}/><form key={edit?.id??'new'} className="editor-form inset-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({resource:'projects',action:edit?'update':'create',id:edit?.id,data:{title:f.get('title'),summary:f.get('summary'),tags:f.get('tags'),repoUrl:f.get('repoUrl'),liveUrl:f.get('liveUrl'),imageKey,featured:f.get('featured')==='on',sortOrder:Number(f.get('sortOrder'))}})}}><h2>{edit?'Edit project':'Add project'}</h2><div className="form-grid"><Input label="Title" name="title" defaultValue={edit?.title??''} required/><Input label="Display order" name="sortOrder" type="number" min="0" defaultValue={edit?.sortOrder??items.length+1} required/><Input label="Repository URL" name="repoUrl" type="url" defaultValue={edit?.repoUrl??''}/><Input label="Live URL" name="liveUrl" type="url" defaultValue={edit?.liveUrl??''}/></div><Input label="Tags, comma separated" name="tags" defaultValue={edit?.tags??''} required/><Textarea label="Summary" name="summary" rows={4} defaultValue={edit?.summary??''} required/><label className="check"><input type="checkbox" name="featured" defaultChecked={edit?.featured??true}/> Show on public site</label><ImageField value={imageKey} onChange={setImageKey}/><div className="form-actions"><Submit busy={busy} label={edit?'Update project':'Add project'}/>{edit&&<button type="button" onClick={()=>select(null)}>Cancel</button>}</div></form></> }

function PublicationEditor({items,busy,onSave}:{items:Publication[];busy:boolean;onSave:(c:SaveCommand)=>void}) { const [edit,setEdit]=useState<Publication|null>(null);const [imageKey,setImageKey]=useState<string|null>(null);const select=(item:Publication|null)=>{setEdit(item);setImageKey(item?.imageKey??null)}; return <><Heading eyebrow="Publications" title="The research library" copy="Maintain publication metadata and destination links."/><ItemList items={items} onEdit={select} onDelete={id=>onSave({resource:'publications',action:'delete',id})}/><form key={edit?.id??'new'} className="editor-form inset-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({resource:'publications',action:edit?'update':'create',id:edit?.id,data:{title:f.get('title'),authors:f.get('authors'),venue:f.get('venue'),year:Number(f.get('year')),summary:f.get('summary'),url:f.get('url'),imageKey,sortOrder:Number(f.get('sortOrder'))}})}}><h2>{edit?'Edit publication':'Add publication'}</h2><Input label="Title" name="title" defaultValue={edit?.title??''} required/><div className="form-grid"><Input label="Venue" name="venue" defaultValue={edit?.venue??''} required/><Input label="Year" name="year" type="number" min="1900" max="2100" defaultValue={edit?.year??new Date().getFullYear()} required/><Input label="Publication URL" name="url" type="url" defaultValue={edit?.url??''} required/><Input label="Display order" name="sortOrder" type="number" min="0" defaultValue={edit?.sortOrder??items.length+1} required/></div><Input label="Authors" name="authors" defaultValue={edit?.authors??''} required/><Textarea label="Summary" name="summary" rows={4} defaultValue={edit?.summary??''} required/><ImageField value={imageKey} onChange={setImageKey}/><div className="form-actions"><Submit busy={busy} label={edit?'Update publication':'Add publication'}/>{edit&&<button type="button" onClick={()=>select(null)}>Cancel</button>}</div></form></> }

function CoordinatePicker({lat,lng,onChange}:{lat:number;lng:number;onChange:(lat:number,lng:number)=>void}) { const collection=feature(world as any,(world as any).objects.countries) as any;const projection=geoNaturalEarth1().fitExtent([[12,12],[988,488]],collection);const path=geoPath(projection);const point=projection([lng,lat]);return <svg className="coordinate-picker" viewBox="0 0 1000 500" onClick={e=>{const rect=e.currentTarget.getBoundingClientRect();const coords:[number,number]=[(e.clientX-rect.left)*1000/rect.width,(e.clientY-rect.top)*500/rect.height];const result=projection.invert?.(coords);if(result)onChange(Number(result[1].toFixed(4)),Number(result[0].toFixed(4)))}} role="img" aria-label="Click the world map to set the city location"><g>{collection.features.map((item:any,i:number)=><path key={item.id??i} d={path(item)??''}/>)}</g>{point&&<circle cx={point[0]} cy={point[1]} r="9"/>}</svg> }
function PlaceEditor({items,busy,onSave}:{items:Place[];busy:boolean;onSave:(c:SaveCommand)=>void}) { const [edit,setEdit]=useState<Place|null>(null);const [lat,setLat]=useState(40.7128);const [lng,setLng]=useState(-74.006);const select=(item:Place|null)=>{setEdit(item);setLat(item?.latitude??40.7128);setLng(item?.longitude??-74.006)};return <><Heading eyebrow="Travel" title="The city index" copy="Add a city, then click the map or fine-tune the coordinates."/><ItemList items={items} onEdit={select} onDelete={id=>onSave({resource:'places',action:'delete',id})}/><form key={edit?.id??'new'} className="editor-form inset-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({resource:'places',action:edit?'update':'create',id:edit?.id,data:{city:f.get('city'),country:f.get('country'),latitude:lat,longitude:lng,year:f.get('year')?Number(f.get('year')):null,note:f.get('note'),sortOrder:Number(f.get('sortOrder'))}})}}><h2>{edit?'Edit city':'Add city'}</h2><CoordinatePicker lat={lat} lng={lng} onChange={(a,b)=>{setLat(a);setLng(b)}}/><div className="form-grid"><Input label="City" name="city" defaultValue={edit?.city??''} required/><Input label="Country" name="country" defaultValue={edit?.country??''} required/><Input label="Latitude" name="latitude" type="number" step="0.0001" value={lat} onChange={e=>setLat(Number(e.target.value))} required/><Input label="Longitude" name="longitude" type="number" step="0.0001" value={lng} onChange={e=>setLng(Number(e.target.value))} required/><Input label="Year (optional)" name="year" type="number" min="1900" max="2100" defaultValue={edit?.year??''}/><Input label="Display order" name="sortOrder" type="number" min="0" defaultValue={edit?.sortOrder??items.length+1} required/></div><Textarea label="Travel note" name="note" rows={3} defaultValue={edit?.note??''}/><div className="form-actions"><Submit busy={busy} label={edit?'Update city':'Add city'}/>{edit&&<button type="button" onClick={()=>select(null)}>Cancel</button>}</div></form></> }

function LiftEditor({items,busy,onSave}:{items:LiftEntry[];busy:boolean;onSave:(c:SaveCommand)=>void}) { const [edit,setEdit]=useState<LiftEntry|null>(null);const [exercise,setExercise]=useState<Exercise>('bench-press');const select=(item:LiftEntry|null)=>{setEdit(item);setExercise(item?.exercise??'bench-press')};return <><Heading eyebrow="Strength" title="The training log" copy="Every saved entry feeds the public progress chart."/><ItemList items={[...items].reverse()} onEdit={select} onDelete={id=>onSave({resource:'lifts',action:'delete',id})}/><form key={edit?.id??'new'} className="editor-form inset-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({resource:'lifts',action:edit?'update':'create',id:edit?.id,data:{date:f.get('date'),exercise,weightLb:exercise==='push-ups'?null:Number(f.get('weightLb')),sets:Number(f.get('sets')),reps:Number(f.get('reps')),notes:f.get('notes')}})}}><h2>{edit?'Edit session':'Log a session'}</h2><div className="form-grid"><Input label="Date" name="date" type="date" defaultValue={edit?.date??new Date().toISOString().slice(0,10)} required/><label>Exercise<select name="exercise" value={exercise} onChange={e=>setExercise(e.target.value as Exercise)}>{(Object.keys(exerciseLabels) as Exercise[]).map(key=><option key={key} value={key}>{exerciseLabels[key]}</option>)}</select></label>{exercise!=='push-ups'&&<Input label="Weight (lb)" name="weightLb" type="number" min="1" step="0.5" defaultValue={edit?.weightLb??''} required/>}<Input label="Sets" name="sets" type="number" min="1" defaultValue={edit?.sets??3} required/><Input label="Reps per set" name="reps" type="number" min="1" defaultValue={edit?.reps??5} required/></div><Textarea label="Notes" name="notes" rows={3} defaultValue={edit?.notes??''}/><div className="form-actions"><Submit busy={busy} label={edit?'Update session':'Add session'}/>{edit&&<button type="button" onClick={()=>select(null)}>Cancel</button>}</div></form></> }
