// Applied atomically once; every statement is guarded for concurrent cold starts.
export const projectMigrationSql = [
  "UPDATE projects SET featured = 0, sort_order = 10 WHERE repo_url = 'https://github.com/P-bhandari/Opencv-Tutorials' AND NOT EXISTS (SELECT 1 FROM site_content_migrations WHERE name = 'portfolio-catalog-2026-09-14')",
  "UPDATE projects SET featured = 1, sort_order = 1, image_key = COALESCE(image_key, '/projects/nutrition-scanner.png') WHERE repo_url = 'https://github.com/P-bhandari/ingredient-scanner' AND NOT EXISTS (SELECT 1 FROM site_content_migrations WHERE name = 'portfolio-catalog-2026-09-14')",
  "UPDATE projects SET featured = 1, sort_order = 2, live_url = CASE WHEN RTRIM(live_url, '/') = 'https://nearby-events.bhandaripiyush5.chatgpt.site' THEN NULL ELSE live_url END WHERE repo_url = 'https://github.com/P-bhandari/nearby-events' AND NOT EXISTS (SELECT 1 FROM site_content_migrations WHERE name = 'portfolio-catalog-2026-09-14')",
  "INSERT INTO projects (title, summary, tags, repo_url, live_url, image_key, featured, published, archived, sort_order) SELECT 'Nutrition Scanner', 'A searchable supplement-label database built on NIH data, distinguishing third-party certifications from self-asserted claims.', 'React, TypeScript, Data product', 'https://github.com/P-bhandari/ingredient-scanner', 'https://p-bhandari.github.io/ingredient-scanner/', '/projects/nutrition-scanner.png', 1, 1, 0, 1 WHERE NOT EXISTS (SELECT 1 FROM projects WHERE LOWER(RTRIM(repo_url, '/')) = LOWER('https://github.com/P-bhandari/ingredient-scanner')) AND NOT EXISTS (SELECT 1 FROM site_content_migrations WHERE name = 'portfolio-catalog-2026-09-14')",
  "INSERT INTO projects (title, summary, tags, repo_url, live_url, image_key, featured, published, archived, sort_order) SELECT 'Date Night', 'A weekly date-night planner for Brooklyn and Manhattan.', 'TypeScript, Events, New York City', 'https://github.com/P-bhandari/nearby-events', NULL, NULL, 1, 1, 0, 2 WHERE NOT EXISTS (SELECT 1 FROM projects WHERE LOWER(RTRIM(repo_url, '/')) = LOWER('https://github.com/P-bhandari/nearby-events')) AND NOT EXISTS (SELECT 1 FROM site_content_migrations WHERE name = 'portfolio-catalog-2026-09-14')",
  "INSERT INTO projects (title, summary, tags, repo_url, live_url, image_key, featured, published, archived, sort_order) SELECT 'Personal Atlas', 'An interactive portfolio combining an illustrated island, product work, research, and an owner-managed content dashboard.', 'React, TypeScript, Cloudflare', 'https://github.com/P-bhandari/About-Me', NULL, NULL, 1, 1, 0, 3 WHERE NOT EXISTS (SELECT 1 FROM projects WHERE LOWER(RTRIM(repo_url, '/')) = LOWER('https://github.com/P-bhandari/About-Me')) AND NOT EXISTS (SELECT 1 FROM site_content_migrations WHERE name = 'portfolio-catalog-2026-09-14')",
  "INSERT INTO projects (title, summary, tags, repo_url, live_url, image_key, featured, published, archived, sort_order) SELECT 'OpenCV Tutorials', 'Annotated C++ implementations of classical image-processing algorithms using OpenCV.', 'C++', 'https://github.com/P-bhandari/Opencv-Tutorials', NULL, NULL, 0, 1, 0, 10 WHERE NOT EXISTS (SELECT 1 FROM projects WHERE LOWER(RTRIM(repo_url, '/')) = LOWER('https://github.com/P-bhandari/Opencv-Tutorials')) AND NOT EXISTS (SELECT 1 FROM site_content_migrations WHERE name = 'portfolio-catalog-2026-09-14')",
  "INSERT INTO projects (title, summary, tags, repo_url, live_url, image_key, featured, published, archived, sort_order) SELECT 'Stereo Matching', 'C++ implementation of sparse-to-dense stereo matching for depth estimation from image pairs, with code for the KITTI and Middlebury benchmarks. Classical, pre-deep-learning approach. Written 2017.', 'C++', 'https://github.com/P-bhandari/stereo_matching', NULL, NULL, 0, 1, 0, 11 WHERE NOT EXISTS (SELECT 1 FROM projects WHERE LOWER(RTRIM(repo_url, '/')) = LOWER('https://github.com/P-bhandari/stereo_matching')) AND NOT EXISTS (SELECT 1 FROM site_content_migrations WHERE name = 'portfolio-catalog-2026-09-14')",
  "INSERT INTO projects (title, summary, tags, repo_url, live_url, image_key, featured, published, archived, sort_order) SELECT 'Intraday Trading Algorithms', 'Trading algos for intraday', 'Jupyter Notebook', 'https://github.com/P-bhandari/Intra-day-trading-algos', NULL, NULL, 0, 1, 0, 12 WHERE NOT EXISTS (SELECT 1 FROM projects WHERE LOWER(RTRIM(repo_url, '/')) = LOWER('https://github.com/P-bhandari/Intra-day-trading-algos')) AND NOT EXISTS (SELECT 1 FROM site_content_migrations WHERE name = 'portfolio-catalog-2026-09-14')",
  "INSERT INTO projects (title, summary, tags, repo_url, live_url, image_key, featured, published, archived, sort_order) SELECT 'Breast Profile Segmentation', 'Automated breast profile segmentation for ROI detection in digital mammograms, evaluated on the mini-MIAS database. C++, with image-processing routines implemented from scratch rather than via OpenCV. Written 2017.', 'C++', 'https://github.com/P-bhandari/Breast_Profile_Segmentation', NULL, NULL, 0, 1, 0, 13 WHERE NOT EXISTS (SELECT 1 FROM projects WHERE LOWER(RTRIM(repo_url, '/')) = LOWER('https://github.com/P-bhandari/Breast_Profile_Segmentation')) AND NOT EXISTS (SELECT 1 FROM site_content_migrations WHERE name = 'portfolio-catalog-2026-09-14')",
  "INSERT INTO projects (title, summary, tags, repo_url, live_url, image_key, featured, published, archived, sort_order) SELECT 'Emotion Recognition', 'Facial expression classification with convolutional neural networks, trained on the JAFFE dataset. Python; compares several architectures. MIT licensed. Written 2017.', 'Python', 'https://github.com/P-bhandari/Emotion-Recognition', NULL, NULL, 0, 1, 0, 14 WHERE NOT EXISTS (SELECT 1 FROM projects WHERE LOWER(RTRIM(repo_url, '/')) = LOWER('https://github.com/P-bhandari/Emotion-Recognition')) AND NOT EXISTS (SELECT 1 FROM site_content_migrations WHERE name = 'portfolio-catalog-2026-09-14')",
  "INSERT INTO projects (title, summary, tags, repo_url, live_url, image_key, featured, published, archived, sort_order) SELECT 'Programming Experiments', 'A collection of programming experiments in image processing, machine learning, Java, MATLAB, and search.', 'Jupyter Notebook', 'https://github.com/P-bhandari/Programs', NULL, NULL, 0, 1, 0, 15 WHERE NOT EXISTS (SELECT 1 FROM projects WHERE LOWER(RTRIM(repo_url, '/')) = LOWER('https://github.com/P-bhandari/Programs')) AND NOT EXISTS (SELECT 1 FROM site_content_migrations WHERE name = 'portfolio-catalog-2026-09-14')",
  "INSERT INTO projects (title, summary, tags, repo_url, live_url, image_key, featured, published, archived, sort_order) SELECT 'LegalTech', 'Algorithms and solutions on legal tech.', 'HTML', 'https://github.com/P-bhandari/LegalTech', NULL, NULL, 0, 1, 1, 16 WHERE NOT EXISTS (SELECT 1 FROM projects WHERE LOWER(RTRIM(repo_url, '/')) = LOWER('https://github.com/P-bhandari/LegalTech')) AND NOT EXISTS (SELECT 1 FROM site_content_migrations WHERE name = 'portfolio-catalog-2026-09-14')",
  "INSERT INTO projects (title, summary, tags, repo_url, live_url, image_key, featured, published, archived, sort_order) SELECT 'Android Mock Location', 'Android demo app for setting mock GPS coordinates via the platform test-provider API. Built to test location-dependent features without physically relocating. Written 2019.', 'Java', 'https://github.com/P-bhandari/android-mock-location', NULL, NULL, 0, 1, 1, 17 WHERE NOT EXISTS (SELECT 1 FROM projects WHERE LOWER(RTRIM(repo_url, '/')) = LOWER('https://github.com/P-bhandari/android-mock-location')) AND NOT EXISTS (SELECT 1 FROM site_content_migrations WHERE name = 'portfolio-catalog-2026-09-14')",
  "INSERT INTO projects (title, summary, tags, repo_url, live_url, image_key, featured, published, archived, sort_order) SELECT 'Self-Taught Learning', 'Matlab code for self-taught-learning using auto enchoders ', 'Matlab', 'https://github.com/P-bhandari/Self_Taught_Learning', NULL, NULL, 0, 1, 1, 18 WHERE NOT EXISTS (SELECT 1 FROM projects WHERE LOWER(RTRIM(repo_url, '/')) = LOWER('https://github.com/P-bhandari/Self_Taught_Learning')) AND NOT EXISTS (SELECT 1 FROM site_content_migrations WHERE name = 'portfolio-catalog-2026-09-14')",
  "INSERT OR IGNORE INTO site_content_migrations (name) VALUES ('portfolio-catalog-2026-09-14')"
];
