import type { Project } from './site-data';

// Public repository metadata reviewed on 2026-09-14. Maintained through the owner dashboard.
export const projectCatalog: Project[] = [
  {
    "id": 2,
    "title": "Nutrition Scanner",
    "summary": "A searchable supplement-label database built on NIH data, distinguishing third-party certifications from self-asserted claims.",
    "tags": "React, TypeScript, Data product",
    "repoUrl": "https://github.com/P-bhandari/ingredient-scanner",
    "liveUrl": "https://p-bhandari.github.io/ingredient-scanner/",
    "imageKey": "/projects/nutrition-scanner.png",
    "featured": true,
    "published": true,
    "archived": false,
    "sortOrder": 1
  },
  {
    "id": 3,
    "title": "Date Night",
    "summary": "A weekly date-night planner for Brooklyn and Manhattan.",
    "tags": "TypeScript, Events, New York City",
    "repoUrl": "https://github.com/P-bhandari/nearby-events",
    "liveUrl": null,
    "imageKey": null,
    "featured": true,
    "published": true,
    "archived": false,
    "sortOrder": 2
  },
  {
    "id": 4,
    "title": "Personal Atlas",
    "summary": "An interactive portfolio combining an illustrated island, product work, research, and an owner-managed content dashboard.",
    "tags": "React, TypeScript, Cloudflare",
    "repoUrl": "https://github.com/P-bhandari/About-Me",
    "liveUrl": null,
    "imageKey": null,
    "featured": true,
    "published": true,
    "archived": false,
    "sortOrder": 3
  },
  {
    "id": 1,
    "title": "OpenCV Tutorials",
    "summary": "Annotated C++ implementations of classical image-processing algorithms using OpenCV.",
    "tags": "C++",
    "repoUrl": "https://github.com/P-bhandari/Opencv-Tutorials",
    "liveUrl": null,
    "imageKey": null,
    "featured": false,
    "published": true,
    "archived": false,
    "sortOrder": 10
  },
  {
    "id": 11,
    "title": "Stereo Matching",
    "summary": "C++ implementation of sparse-to-dense stereo matching for depth estimation from image pairs, with code for the KITTI and Middlebury benchmarks. Classical, pre-deep-learning approach. Written 2017.",
    "tags": "C++",
    "repoUrl": "https://github.com/P-bhandari/stereo_matching",
    "liveUrl": null,
    "imageKey": null,
    "featured": false,
    "published": true,
    "archived": false,
    "sortOrder": 11
  },
  {
    "id": 12,
    "title": "Intraday Trading Algorithms",
    "summary": "Trading algos for intraday",
    "tags": "Jupyter Notebook",
    "repoUrl": "https://github.com/P-bhandari/Intra-day-trading-algos",
    "liveUrl": null,
    "imageKey": null,
    "featured": false,
    "published": true,
    "archived": false,
    "sortOrder": 12
  },
  {
    "id": 13,
    "title": "Breast Profile Segmentation",
    "summary": "Automated breast profile segmentation for ROI detection in digital mammograms, evaluated on the mini-MIAS database. C++, with image-processing routines implemented from scratch rather than via OpenCV. Written 2017.",
    "tags": "C++",
    "repoUrl": "https://github.com/P-bhandari/Breast_Profile_Segmentation",
    "liveUrl": null,
    "imageKey": null,
    "featured": false,
    "published": true,
    "archived": false,
    "sortOrder": 13
  },
  {
    "id": 14,
    "title": "Emotion Recognition",
    "summary": "Facial expression classification with convolutional neural networks, trained on the JAFFE dataset. Python; compares several architectures. MIT licensed. Written 2017.",
    "tags": "Python",
    "repoUrl": "https://github.com/P-bhandari/Emotion-Recognition",
    "liveUrl": null,
    "imageKey": null,
    "featured": false,
    "published": true,
    "archived": false,
    "sortOrder": 14
  },
  {
    "id": 15,
    "title": "Programming Experiments",
    "summary": "A collection of programming experiments in image processing, machine learning, Java, MATLAB, and search.",
    "tags": "Jupyter Notebook",
    "repoUrl": "https://github.com/P-bhandari/Programs",
    "liveUrl": null,
    "imageKey": null,
    "featured": false,
    "published": true,
    "archived": false,
    "sortOrder": 15
  },
  {
    "id": 16,
    "title": "LegalTech",
    "summary": "Algorithms and solutions on legal tech.",
    "tags": "HTML",
    "repoUrl": "https://github.com/P-bhandari/LegalTech",
    "liveUrl": null,
    "imageKey": null,
    "featured": false,
    "published": true,
    "archived": true,
    "sortOrder": 16
  },
  {
    "id": 17,
    "title": "Android Mock Location",
    "summary": "Android demo app for setting mock GPS coordinates via the platform test-provider API. Built to test location-dependent features without physically relocating. Written 2019.",
    "tags": "Java",
    "repoUrl": "https://github.com/P-bhandari/android-mock-location",
    "liveUrl": null,
    "imageKey": null,
    "featured": false,
    "published": true,
    "archived": true,
    "sortOrder": 17
  },
  {
    "id": 18,
    "title": "Self-Taught Learning",
    "summary": "Matlab code for self-taught-learning using auto enchoders ",
    "tags": "Matlab",
    "repoUrl": "https://github.com/P-bhandari/Self_Taught_Learning",
    "liveUrl": null,
    "imageKey": null,
    "featured": false,
    "published": true,
    "archived": true,
    "sortOrder": 18
  }
];
